// Wheel of Fortune Puzzle Bank
// Add your own puzzles below! Each puzzle needs a category and puzzle text.
// Categories: PHRASE, THING, PLACE, PERSON, TITLE
// Rules: ALL CAPS, no apostrophes or punctuation, spaces between words only.

const PUZZLES = [
  // PHRASE
  { category: "PHRASE", puzzle: "BETTER LATE THAN NEVER" },
  { category: "PHRASE", puzzle: "ACTIONS SPEAK LOUDER THAN WORDS" },
  { category: "PHRASE", puzzle: "EVERY CLOUD HAS A SILVER LINING" },
  { category: "PHRASE", puzzle: "BITE OFF MORE THAN YOU CAN CHEW" },
  { category: "PHRASE", puzzle: "THE EARLY BIRD CATCHES THE WORM" },
  { category: "PHRASE", puzzle: "LAUGHTER IS THE BEST MEDICINE" },
  { category: "PHRASE", puzzle: "DONT JUDGE A BOOK BY ITS COVER" },
  { category: "PHRASE", puzzle: "PRACTICE MAKES PERFECT" },
  { category: "PHRASE", puzzle: "WHEN IN DOUBT LEAVE IT OUT" },
  { category: "PHRASE", puzzle: "TWO WRONGS DONT MAKE A RIGHT" },
  { category: "PHRASE", puzzle: "KILL TWO BIRDS WITH ONE STONE" },
  { category: "PHRASE", puzzle: "THE BALL IS IN YOUR COURT" },
  { category: "PHRASE", puzzle: "HIT THE NAIL ON THE HEAD" },
  { category: "PHRASE", puzzle: "BREAK A LEG" },
  { category: "PHRASE", puzzle: "BURN THE MIDNIGHT OIL" },
  { category: "PHRASE", puzzle: "ONCE IN A BLUE MOON" },
  { category: "PHRASE", puzzle: "BITE THE BULLET" },
  { category: "PHRASE", puzzle: "SPILL THE BEANS" },
  { category: "PHRASE", puzzle: "UNDER THE WEATHER" },
  { category: "PHRASE", puzzle: "ADD FUEL TO THE FIRE" },
  { category: "PHRASE", puzzle: "BACK TO SQUARE ONE" },
  { category: "PHRASE", puzzle: "BEAT AROUND THE BUSH" },
  { category: "PHRASE", puzzle: "COSTS AN ARM AND A LEG" },
  { category: "PHRASE", puzzle: "CUT TO THE CHASE" },
  { category: "PHRASE", puzzle: "DONT CRY OVER SPILLED MILK" },
  { category: "PHRASE", puzzle: "EVERY DOG HAS ITS DAY" },
  { category: "PHRASE", puzzle: "GET OUT OF HAND" },
  { category: "PHRASE", puzzle: "HIT THE SACK" },
  { category: "PHRASE", puzzle: "IN THE HEAT OF THE MOMENT" },
  { category: "PHRASE", puzzle: "JUMP ON THE BANDWAGON" },
  { category: "PHRASE", puzzle: "KEEP YOUR CHIN UP" },
  { category: "PHRASE", puzzle: "LET THE CAT OUT OF THE BAG" },
  { category: "PHRASE", puzzle: "MISS THE BOAT" },
  { category: "PHRASE", puzzle: "NO PAIN NO GAIN" },
  { category: "PHRASE", puzzle: "ON THE FENCE" },
  { category: "PHRASE", puzzle: "PULLING YOUR LEG" },
  { category: "PHRASE", puzzle: "TAKE IT WITH A GRAIN OF SALT" },
  { category: "PHRASE", puzzle: "THE BEST OF BOTH WORLDS" },
  { category: "PHRASE", puzzle: "TIE UP LOOSE ENDS" },
  { category: "PHRASE", puzzle: "TIME FLIES WHEN YOURE HAVING FUN" },
  { category: "PHRASE", puzzle: "TURN OVER A NEW LEAF" },
  { category: "PHRASE", puzzle: "UNDER THE TABLE" },
  { category: "PHRASE", puzzle: "YOU CANT HAVE YOUR CAKE AND EAT IT TOO" },
  { category: "PHRASE", puzzle: "BACK TO BASICS" },
  { category: "PHRASE", puzzle: "GIVE IT YOUR BEST SHOT" },
  { category: "PHRASE", puzzle: "GO THE EXTRA MILE" },
  { category: "PHRASE", puzzle: "HANG IN THERE" },
  { category: "PHRASE", puzzle: "IT TAKES TWO TO TANGO" },
  { category: "PHRASE", puzzle: "LAST BUT NOT LEAST" },
  { category: "PHRASE", puzzle: "LOOK BEFORE YOU LEAP" },
  { category: "PHRASE", puzzle: "MAKE HAY WHILE THE SUN SHINES" },
  { category: "PHRASE", puzzle: "ON CLOUD NINE" },
  { category: "PHRASE", puzzle: "ONCE BITTEN TWICE SHY" },
  { category: "PHRASE", puzzle: "READ BETWEEN THE LINES" },
  { category: "PHRASE", puzzle: "SEE EYE TO EYE" },
  { category: "PHRASE", puzzle: "SHOOT FOR THE STARS" },
  { category: "PHRASE", puzzle: "SITTING ON TOP OF THE WORLD" },
  { category: "PHRASE", puzzle: "STRIKE WHILE THE IRON IS HOT" },
  { category: "PHRASE", puzzle: "THE SKY IS THE LIMIT" },
  { category: "PHRASE", puzzle: "THROW CAUTION TO THE WIND" },
  { category: "PHRASE", puzzle: "TOO MANY COOKS SPOIL THE BROTH" },
  { category: "PHRASE", puzzle: "WHEN PIGS FLY" },
  { category: "PHRASE", puzzle: "YOURE ON THIN ICE" },
  { category: "PHRASE", puzzle: "A PENNY FOR YOUR THOUGHTS" },
  { category: "PHRASE", puzzle: "ALL THAT GLITTERS IS NOT GOLD" },
  { category: "PHRASE", puzzle: "BITE THE HAND THAT FEEDS YOU" },
  { category: "PHRASE", puzzle: "CURIOSITY KILLED THE CAT" },
  { category: "PHRASE", puzzle: "DONT BITE OFF MORE THAN YOU CAN CHEW" },
  { category: "PHRASE", puzzle: "EASY COME EASY GO" },
  { category: "PHRASE", puzzle: "FORTUNE FAVORS THE BOLD" },

  // THING
  { category: "THING", puzzle: "ROLLER COASTER" },
  { category: "THING", puzzle: "SWIMMING POOL" },
  { category: "THING", puzzle: "BIRTHDAY CAKE" },
  { category: "THING", puzzle: "SKATEBOARD" },
  { category: "THING", puzzle: "SOLAR SYSTEM" },
  { category: "THING", puzzle: "THUNDERSTORM" },
  { category: "THING", puzzle: "BASKETBALL HOOP" },
  { category: "THING", puzzle: "TREASURE CHEST" },
  { category: "THING", puzzle: "FIRE HYDRANT" },
  { category: "THING", puzzle: "CANDY BAR" },
  { category: "THING", puzzle: "ALARM CLOCK" },
  { category: "THING", puzzle: "CREDIT CARD" },
  { category: "THING", puzzle: "CELL PHONE" },
  { category: "THING", puzzle: "COFFEE MAKER" },
  { category: "THING", puzzle: "LAWN MOWER" },
  { category: "THING", puzzle: "FIRE TRUCK" },
  { category: "THING", puzzle: "PIGGY BANK" },
  { category: "THING", puzzle: "REMOTE CONTROL" },
  { category: "THING", puzzle: "ROCKING CHAIR" },
  { category: "THING", puzzle: "SNOW GLOBE" },
  { category: "THING", puzzle: "SPEED BUMP" },
  { category: "THING", puzzle: "TRAFFIC LIGHT" },
  { category: "THING", puzzle: "WATER BALLOON" },
  { category: "THING", puzzle: "WINDSHIELD WIPER" },
  { category: "THING", puzzle: "BASEBALL DIAMOND" },
  { category: "THING", puzzle: "BUBBLE WRAP" },
  { category: "THING", puzzle: "CEILING FAN" },
  { category: "THING", puzzle: "CHOPSTICKS" },
  { category: "THING", puzzle: "COMPASS" },
  { category: "THING", puzzle: "DIVING BOARD" },
  { category: "THING", puzzle: "DOOR KNOCKER" },
  { category: "THING", puzzle: "ESCALATOR" },
  { category: "THING", puzzle: "FISHING ROD" },
  { category: "THING", puzzle: "FLASHLIGHT" },
  { category: "THING", puzzle: "GARDEN HOSE" },
  { category: "THING", puzzle: "GRADUATION CAP" },
  { category: "THING", puzzle: "HAMMOCK" },
  { category: "THING", puzzle: "ICE CREAM CONE" },
  { category: "THING", puzzle: "JACK IN THE BOX" },
  { category: "THING", puzzle: "KALEIDOSCOPE" },
  { category: "THING", puzzle: "MAGIC CARPET" },
  { category: "THING", puzzle: "NEWSPAPER" },
  { category: "THING", puzzle: "PAPER AIRPLANE" },
  { category: "THING", puzzle: "PARKING METER" },
  { category: "THING", puzzle: "RUBBER DUCK" },
  { category: "THING", puzzle: "SCARECROW" },
  { category: "THING", puzzle: "SHOPPING CART" },
  { category: "THING", puzzle: "SMOKE ALARM" },
  { category: "THING", puzzle: "TRAMPOLINE" },
  { category: "THING", puzzle: "UMBRELLA" },
  { category: "THING", puzzle: "VENDING MACHINE" },
  { category: "THING", puzzle: "WEATHERVANE" },
  { category: "THING", puzzle: "WHEELBARROW" },
  { category: "THING", puzzle: "WIND CHIME" },
  { category: "THING", puzzle: "WISHING WELL" },
  { category: "THING", puzzle: "YO YO" },
  { category: "THING", puzzle: "ZIPPER" },
  { category: "THING", puzzle: "BOARD GAME" },
  { category: "THING", puzzle: "BUNK BED" },
  { category: "THING", puzzle: "BUMPER STICKER" },

  // PLACE
  { category: "PLACE", puzzle: "GRAND CANYON" },
  { category: "PLACE", puzzle: "STATUE OF LIBERTY" },
  { category: "PLACE", puzzle: "TIMES SQUARE" },
  { category: "PLACE", puzzle: "NIAGARA FALLS" },
  { category: "PLACE", puzzle: "YELLOWSTONE NATIONAL PARK" },
  { category: "PLACE", puzzle: "MOUNT RUSHMORE" },
  { category: "PLACE", puzzle: "GOLDEN GATE BRIDGE" },
  { category: "PLACE", puzzle: "EMPIRE STATE BUILDING" },
  { category: "PLACE", puzzle: "DISNEY WORLD" },
  { category: "PLACE", puzzle: "HOLLYWOOD HILLS" },
  { category: "PLACE", puzzle: "LAS VEGAS STRIP" },
  { category: "PLACE", puzzle: "THE ALAMO" },
  { category: "PLACE", puzzle: "CENTRAL PARK" },
  { category: "PLACE", puzzle: "CAPE CANAVERAL" },
  { category: "PLACE", puzzle: "ROCKY MOUNTAINS" },
  { category: "PLACE", puzzle: "THE WHITE HOUSE" },
  { category: "PLACE", puzzle: "MONUMENT VALLEY" },
  { category: "PLACE", puzzle: "MOUNT OLYMPUS" },
  { category: "PLACE", puzzle: "DEATH VALLEY" },
  { category: "PLACE", puzzle: "GREAT SMOKY MOUNTAINS" },
  { category: "PLACE", puzzle: "HOOVER DAM" },
  { category: "PLACE", puzzle: "LINCOLN MEMORIAL" },
  { category: "PLACE", puzzle: "MISSISSIPPI RIVER" },
  { category: "PLACE", puzzle: "MOUNT WHITNEY" },
  { category: "PLACE", puzzle: "PAINTED DESERT" },
  { category: "PLACE", puzzle: "PENTAGON" },
  { category: "PLACE", puzzle: "GRAND TETON NATIONAL PARK" },
  { category: "PLACE", puzzle: "SAN FRANCISCO BAY" },
  { category: "PLACE", puzzle: "SEQUOIA NATIONAL PARK" },
  { category: "PLACE", puzzle: "SILICON VALLEY" },
  { category: "PLACE", puzzle: "WASHINGTON MONUMENT" },
  { category: "PLACE", puzzle: "YOSEMITE VALLEY" },
  { category: "PLACE", puzzle: "THE GREAT BARRIER REEF" },
  { category: "PLACE", puzzle: "AMAZON RAINFOREST" },
  { category: "PLACE", puzzle: "EIFFEL TOWER" },
  { category: "PLACE", puzzle: "MOUNT EVEREST" },
  { category: "PLACE", puzzle: "SAHARA DESERT" },
  { category: "PLACE", puzzle: "THE COLOSSEUM" },
  { category: "PLACE", puzzle: "GREAT WALL OF CHINA" },
  { category: "PLACE", puzzle: "BUCKINGHAM PALACE" },
  { category: "PLACE", puzzle: "MACHU PICCHU" },
  { category: "PLACE", puzzle: "THE PYRAMIDS OF GIZA" },
  { category: "PLACE", puzzle: "STONEHENGE" },
  { category: "PLACE", puzzle: "SYDNEY OPERA HOUSE" },
  { category: "PLACE", puzzle: "TAJ MAHAL" },
  { category: "PLACE", puzzle: "TIMES SQUARE" },
  { category: "PLACE", puzzle: "VENICE ITALY" },

  // PERSON
  { category: "PERSON", puzzle: "ALBERT EINSTEIN" },
  { category: "PERSON", puzzle: "MARTIN LUTHER KING JR" },
  { category: "PERSON", puzzle: "AMELIA EARHART" },
  { category: "PERSON", puzzle: "THOMAS EDISON" },
  { category: "PERSON", puzzle: "NEIL ARMSTRONG" },
  { category: "PERSON", puzzle: "ABRAHAM LINCOLN" },
  { category: "PERSON", puzzle: "GEORGE WASHINGTON" },
  { category: "PERSON", puzzle: "BENJAMIN FRANKLIN" },
  { category: "PERSON", puzzle: "CHRISTOPHER COLUMBUS" },
  { category: "PERSON", puzzle: "HARRIET TUBMAN" },
  { category: "PERSON", puzzle: "LEONARDO DA VINCI" },
  { category: "PERSON", puzzle: "MARIE CURIE" },
  { category: "PERSON", puzzle: "MICHAEL JORDAN" },
  { category: "PERSON", puzzle: "OPRAH WINFREY" },
  { category: "PERSON", puzzle: "SERENA WILLIAMS" },
  { category: "PERSON", puzzle: "STEPHEN HAWKING" },
  { category: "PERSON", puzzle: "THEODORE ROOSEVELT" },
  { category: "PERSON", puzzle: "WALT DISNEY" },
  { category: "PERSON", puzzle: "WRIGHT BROTHERS" },
  { category: "PERSON", puzzle: "BABE RUTH" },
  { category: "PERSON", puzzle: "BEETHOVEN" },
  { category: "PERSON", puzzle: "CLEOPATRA" },
  { category: "PERSON", puzzle: "GALILEO GALILEI" },
  { category: "PERSON", puzzle: "MAHATMA GANDHI" },
  { category: "PERSON", puzzle: "MARK TWAIN" },
  { category: "PERSON", puzzle: "NAPOLEON BONAPARTE" },
  { category: "PERSON", puzzle: "ROSA PARKS" },
  { category: "PERSON", puzzle: "SIMONE BILES" },
  { category: "PERSON", puzzle: "WILLIAM SHAKESPEARE" },
  { category: "PERSON", puzzle: "USAIN BOLT" },
  { category: "PERSON", puzzle: "JACKIE ROBINSON" },
  { category: "PERSON", puzzle: "HELEN KELLER" },
  { category: "PERSON", puzzle: "ELEANOR ROOSEVELT" },
  { category: "PERSON", puzzle: "CHARLES DARWIN" },
  { category: "PERSON", puzzle: "EDGAR ALLAN POE" },
  { category: "PERSON", puzzle: "FREDDIE MERCURY" },
  { category: "PERSON", puzzle: "JAMES DEAN" },
  { category: "PERSON", puzzle: "LEWIS AND CLARK" },
  { category: "PERSON", puzzle: "MARILYN MONROE" },
  { category: "PERSON", puzzle: "PABLO PICASSO" },

  // TITLE
  { category: "TITLE", puzzle: "THE LION KING" },
  { category: "TITLE", puzzle: "SCHOOL OF ROCK" },
  { category: "TITLE", puzzle: "SPIDER MAN INTO THE SPIDER VERSE" },
  { category: "TITLE", puzzle: "BACK TO THE FUTURE" },
  { category: "TITLE", puzzle: "GUARDIANS OF THE GALAXY" },
  { category: "TITLE", puzzle: "MINECRAFT THE MOVIE" },
  { category: "TITLE", puzzle: "THE WIZARD OF OZ" },
  { category: "TITLE", puzzle: "JURASSIC PARK" },
  { category: "TITLE", puzzle: "HOME ALONE" },
  { category: "TITLE", puzzle: "THE DARK KNIGHT" },
  { category: "TITLE", puzzle: "FINDING NEMO" },
  { category: "TITLE", puzzle: "FORREST GUMP" },
  { category: "TITLE", puzzle: "HARRY POTTER AND THE SORCERERS STONE" },
  { category: "TITLE", puzzle: "INDIANA JONES AND THE TEMPLE OF DOOM" },
  { category: "TITLE", puzzle: "IT IS A WONDERFUL LIFE" },
  { category: "TITLE", puzzle: "PIRATES OF THE CARIBBEAN" },
  { category: "TITLE", puzzle: "SHREK" },
  { category: "TITLE", puzzle: "STAR WARS THE EMPIRE STRIKES BACK" },
  { category: "TITLE", puzzle: "THE AVENGERS" },
  { category: "TITLE", puzzle: "THE INCREDIBLES" },
  { category: "TITLE", puzzle: "TOY STORY" },
  { category: "TITLE", puzzle: "WILLY WONKA AND THE CHOCOLATE FACTORY" },
  { category: "TITLE", puzzle: "THE LITTLE MERMAID" },
  { category: "TITLE", puzzle: "BEAUTY AND THE BEAST" },
  { category: "TITLE", puzzle: "ALADDIN" },
  { category: "TITLE", puzzle: "THE SOUND OF MUSIC" },
  { category: "TITLE", puzzle: "GHOSTBUSTERS" },
  { category: "TITLE", puzzle: "E T THE EXTRA TERRESTRIAL" },
  { category: "TITLE", puzzle: "GREASE" },
  { category: "TITLE", puzzle: "TOP GUN" },
  { category: "TITLE", puzzle: "MISSION IMPOSSIBLE" },
  { category: "TITLE", puzzle: "THE HUNGER GAMES" },
  { category: "TITLE", puzzle: "BLACK PANTHER" },
  { category: "TITLE", puzzle: "WONDER WOMAN" },
  { category: "TITLE", puzzle: "THE SOCIAL NETWORK" },
  { category: "TITLE", puzzle: "FROZEN" },
  { category: "TITLE", puzzle: "MOANA" },
  { category: "TITLE", puzzle: "ENCANTO" },
  { category: "TITLE", puzzle: "COCO" },
  { category: "TITLE", puzzle: "INSIDE OUT" },
  { category: "TITLE", puzzle: "UP" },
  { category: "TITLE", puzzle: "WALL E" },
  { category: "TITLE", puzzle: "RATATOUILLE" },
  { category: "TITLE", puzzle: "MONSTERS INC" },
  { category: "TITLE", puzzle: "A BUGS LIFE" },
  { category: "TITLE", puzzle: "THE PARENT TRAP" },
  { category: "TITLE", puzzle: "NIGHT AT THE MUSEUM" },
  { category: "TITLE", puzzle: "CATCH ME IF YOU CAN" },
  { category: "TITLE", puzzle: "EDWARD SCISSORHANDS" },
  { category: "TITLE", puzzle: "FERRIS BUELLERS DAY OFF" },
];
